from django.conf.urls import patterns, url
from quora import views

urlpatterns = patterns('',
    #url(r'^$', 'quora.views.login_home'),
    url(r'^home/', 'quora.views.scroll_home'),
    url(r'^setpassword/$', 'quora.views.setpass'),
    url(r'^logout/', 'quora.views.logout_view'),
    #url(r'^set_pass/$', 'quora.views.set_pass'),
    url(r'^user_detail/(?P<u_id>\d+)/$', 'quora.views.user_details'),
    url(r'^add-question/$', 'quora.views.saving_question'),
    url(r'^adding_user_desc/(?P<u_id>\d+)/$', 'quora.views.add_user_desc'),
    url(r'^adding_user_full_detail/(?P<u_id>\d+)/$', 'quora.views.adding_full_detail_of_user'),
    #url(r'^title_edit/(?P<e_id>\d+)$', 'quora.views.edit_question_title'),
    url(r'^question/(?P<tags>.+)/(?P<title>.+)/$',
        'quora.views.question_description',),
    url(r'^answer/delete/(?P<a_id>\d+)/$', 'quora.views.answer_delete'),
    url(r'^unanswered-questions/$', 'quora.views.all_unanswered_question'),
    url(r'^comment/(?P<a_id>\d+)/$', 'quora.views.display_comments'),
    url(r'^comment/delete/(?P<a_id>\d+)/(?P<c_id>\d+)/$',
        'quora.views.comment_delete'),
    url(r'^live-search/$', 'quora.views.auto_search'),
    url(r'^question-topic-search/$', 'quora.views.question_topic_search'),
    url(r'^comment-question/(?P<q_id>\d+)/$', 'quora.views.question_comment'),
    url(r'^question-delete/comment/(?P<q_id>\d+)/(?P<c_id>\d+)/$',
         'quora.views.question_comment_delete'),
    url(r'^edit-question/(?P<q_id>\d+)/$', 'quora.views.edit_question'),
    url(r'^delete-question/(?P<q_id>\d+)/$', 'quora.views.question_stream_delete'),
    url(r'^answer-delete/(?P<q_id>\d+)/$', 'quora.views.answer_stream_delete'),
    url(r'^like/(?P<a_id>\d+)/$', 'quora.views.like'),
    url(r'^unlike/(?P<a_id>\d+)/$', 'quora.views.unlike'),
    url(r'^comment/like/(?P<c_id>\d+)/$', 'quora.views.comment_like'),
    url(r'^comment/unlike/(?P<c_id>\d+)/$', 'quora.views.comment_unlike'),
    url(r'^comment/answer/like/(?P<c_id>\d+)/$',
         'quora.views.comment_answer_like'),
    url(r'^comment/answer/unlike/(?P<c_id>\d+)/$',
         'quora.views.comment_answer_unlike'),
    url(r'^user-settings/$', views.user_settings),
    url(r'^change/$', views.change_password),
    url(r'^fresh/$', views.fresh_password),
    url(r'^new/$', views.new_password),
    url(r'^create-topic/$', views.create_topic),
    url(r'^search-results/$', views.search_results),
    url(r'^email/$', views.email_prefrences),
    url(r'^topic-search/(?P<topic>.+)/$', views.search_topic),
    url(r'^trending-topics/$',views.trending_topics),
    url(r'^user_detail_on_hover/(?P<u_id>\d+)/$',views.user_on_hover),
    #url(r'^increased-data/$',views.increased_data),
    #url(r'^decreased-data/$',views.decreased_data),
)
